version: 2.1
orbs:
  win: circleci/windows@2.2.0
  node: circleci/node@4.1.0

jobs:
  one:
    executor: win/default     
    steps:
      - checkout
      - run: dotnet build server/api
      - run:
          command: dotnet run --project  ./server/api
          background: true
      - run: dotnet test ./server/tests
  two:
    executor: node/default
    steps:
      - checkout
      - run: |
          cd hr-app-frontend
          npm install
          npm test

workflows:
  version: 2.1
  one_and_two: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - one
      - two