version: 2.1
orbs:
  win: circleci/windows@2.2.0
  node: circleci/node@4.1.0
  heroku: circleci/heroku@0.0.10

jobs:
  server:
    executor: win/default     
    steps:
      - checkout
      - run: dotnet build server/api
      - run:
          command: dotnet run --project  ./server/api
          background: true
      - run: dotnet test ./server/tests
  hr-app-frontend:
    executor: node/default
    steps:
      - checkout
      - run: |
          cd hr-app-frontend
          npm install
          npm test

workflows:
  version: 2.1
  server_and_hr_app_frontend: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - server
      - hr-app-frontend
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter